# NumPy Assignment

In [1]:
import numpy as np

1. Write a function so that the columns of the output matrix are powers of the input
vector.

    The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

    HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [50]:
x = np.array([1, 2, 3, 5])
N = 3
np.vander(x, N,increasing=False) # predefined vander function in numpy

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

My Soultion:

In [52]:
# custom vander function of vander function in numpy
def generate_vander_matrix(inputvector, n, increase=False):
    
    if not increase: # when increase is False, i-th output column is the input vector raised element-wise to the power of (N - i - 1)
        output_matx = np.array([value**(n-1-i) for value in inputvector for i in range(n)]).reshape(inputvector.size,n)
        
    elif increase: # when increase is True
        output_matx = np.array([value**i for value in inputvector for i in range(n)]).reshape(inputvector.size,n)
    
    return output_matx

In [55]:
print("Output:\n")

inputvector = np.array([1, 2, 3, 4, 5])
no_col_output_matx = 4

# for decrease vender order
output_matx_decrese_order = generate_vander_matrix(inputvector,no_col_output_matx,False)

# for increase vender order
output_matx_increse_order = generate_vander_matrix(inputvector,no_col_output_matx,True)

print(f"The input vector is: {inputvector} \n")

print("Number of columns in output matrix should be:",no_col_output_matx,"\n")

print("Vander matrix of the input array in decreasing order of powers:\n",output_matx_decrese_order,"\n")

print("Vander matrix of the input array in increasing order of powers:\n",output_matx_increse_order,"\n")

Output:

The input vector is: [1 2 3 4 5] 

Number of columns in output matrix should be: 4 

Vander matrix of the input array in decreasing order of powers:
 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]] 

Vander matrix of the input array in increasing order of powers:
 [[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]] 



2. Problem Statement 2:
    Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:

    The moving average sequence has n-k+1 elements as shown below.
    
    The moving averages with k=4 of a ten-value sequence (n=10) is shown below
    
    i 1 2 3 4 5 6 7 8 9 10
    
    ===== == == == == == == == == == ==
    
    Input 10 20 30 40 50 60 70 80 90 100
    
    y1 25 = (10+20+30+40)/4
    
    y2 35 = (20+30+40+50)/4
    
    y3 45 = (30+40+50+60)/4
    
    y4 55 = (40+50+60+70)/4
    
    y5 65 = (50+60+70+80)/4
    
    y6 75 = (60+70+80+90)/4
    
    y7 85 = (70+80+90+100)/4
    
    Thus, the moving average sequence has n-k+1=10-4+1=7 values.

    Question: Write a function to find moving average in an array over a window:

    Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

Solution:

In [71]:
input_list = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

N = 3 # window of 3

cumsum = [0] 
moving_averages = []

for i, x in enumerate(input_list, 1):
    cumsum.append(cumsum[i-1] + x)
    if i>=N:
        moving_average = (cumsum[i] - cumsum[i-N])/N
       
        moving_averages.append(moving_average)

print(f"The moving average sequence has (n-k+1=) {len(input_list) - N + 1} values \n")

print("Movies Averages are:\n", moving_averages)

The moving average sequence has (n-k+1=) 11 values 

Movies Averages are:
 [5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
